Hw 1
matweykai/apartment_layout_control pull request #1
Opened 2024-12-02 17:00 UTC by matweykai

2024-12-04 06:47 UTC, PredelinaAsya requested changes
Привет!

PR был отправлен после жёсткого дедлайна. Но это пусть рассудят преподаватели.

По существу: в целом, всё отлично) Есть только пару небольших замечаний:
 1. В pre-commit мало используются форматтеры: я бы добавила black или ruff
 2. Не очень понятно про метрику качества в блоке про успех итерации: уточни, пожалуйста, в дизайн-документе. Точность — это accuracy? По всем классам дефектов + фоновый или бинарная классификация (есть дефект или нет)? Насколько сбалансированы классы? Если нет, возможно, стоит рассмотреть другую метрику качества

2024-12-04 16:21 UTC, PredelinaAsya approved these changes
@matweykai спасибо, всё отлично! У меня больше нет вопросов

2024-12-04 19:28 UTC, mksgrd requested changes
Привет) Хорошая работа!

Мне не совсем понятно какие именно VLLM используются в проекте. Добавь, пожалуйста, их небольшое описание в дизайн-документ

2024-12-17 16:20 UTC, pacifikus approved these changes
Добрый день!

Спасибо за работу! Отличный дизайн-док, но, к сожалению, сданный по истечении жесткого дедлайна, поэтому не могу выставить баллы... В любом случае, эта работа - фундамент для следующих ДЗ и будет оцениваться при итоговом ревью проекта :)

2024-12-24 11:11 UTC, merged